esperanzabeta <- expression(paste("E[X]" == frac(alpha, (alpha + beta))))
varianzabeta <- expression(paste("Var[X]" == frac(alpha ~ beta, (alpha + beta)^{2} ~ (alpha + beta + 1))))
funciongeneradora <- expression(paste(M[x](t) == sum(frac(Beta(alpha + k, beta), Beta(alpha, beta)) ~ frac(t^{k}, "k!"), k==0, infinity)))
par(mfrow = c(3,1), mar=c(0, 0, 0, 0), oma = c(13, 13, 13, 13))
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = esperanzabeta, cex = 3)
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = varianzabeta, cex = 3)
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = funciongeneradora, cex = 3)

sesgo <- expression(paste("b(T)" == "E[T]" - mu))
par(mfrow = c(3,1), mar=c(0, 0, 0, 0), oma = c(13, 13, 13, 13))
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = sesgo, cex = 3)

precision <- expression(paste("Pr(T)" == frac(1, "Var[X]")))
par(mfrow = c(3,1), mar=c(0, 0, 0, 0), oma = c(5, 5, 5, 5))
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = precision, cex = 3)

ecm <- expression(paste(paste("ECM[T]" == "E[[T-theta]]"^{2}])) == "Var[X]" + "b[T]"^{2})
expression(paste(paste("E[X]" == mu) == 0.5))
par(mfrow = c(3,1), mar=c(0, 0, 0, 0), oma = c(5, 5, 5, 5))
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = ecm, cex = 3)

consistencia_varianza <- expression(paste(paste(lim(Var(T), n %->% infinity))) == "0")
consistencia_sesgo <- expression(paste(paste(lim(b(T), n %->% infinity))) == "0")
par(mfrow = c(3,1), mar=c(0, 0, 0, 0), oma = c(10, 10, 10, 10))
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = consistencia_varianza, cex = 3)
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = consistencia_sesgo, cex = 3)

invarianza_traslaciones <- expression(paste("1)   " , paste(paste(T(a + X[1], ... , a + X[n]))) == a + T(X[1], ... , X[n])))
invarianza_cambioescala <- expression(paste("2)   ", paste(paste(T(b*X[1], ... , b*X[n]))) == b*T(X[1], ... , X[n])))
par(mfrow = c(3,1), mar=c(0, 0, 0, 0), oma = c(10, 10, 10, 10))
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = invarianza_traslaciones, cex = 3)
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = invarianza_cambioescala, cex = 3)

distribucion_uniforme_01 <- expression(paste(X["u"] == "U(0, 1)"))
distribucion_beta <- expression(paste(paste(X[B] == "Beta"))(alpha == 2, beta == 2))
distribucion_uniforme_23 <- expression(paste(X["u'"] == "U(2, 3)"))
distribucion_contaminada <- expression(paste(X[c]) == "")
prob_unif_menorque <- expression(paste(P(X[u]) <= 0.9))
prob_unif_mayorque <- expression(paste(P(X[u]) > 0.9))
par(mfrow = c(6,1), mar=c(0, 0, 0, 0), oma = c(8, 8, 8, 8))
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = distribucion_uniforme_01, cex = 3)
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = distribucion_beta, cex = 3)
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = distribucion_uniforme_23, cex = 3)
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = distribucion_contaminada, cex = 3)
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = prob_unif_menorque, cex = 3)
plot(0, 0, type = "n", xlim = c(-0.25, 0.25), ylim = c(-0.25, 0.25), xaxt = "n", yaxt = "n", ann = FALSE, frame.plot = FALSE)
text(0, 0, labels = prob_unif_mayorque, cex = 3)